# 100 intenciones adicionales de calidad. %s = objeto de la tarea. [label, minutos].
EXTRA = {
 "fregar_platos": {"ex":["fregar los platos","lavar los cacharros","recoger la cocina despues de comer","poner el lavavajillas","fregar todo lo del fregadero"],
   "steps":[["Retirar restos y apilar los platos",3],["Llenar el lavavajillas o el fregadero",4],["Fregar lo que no cabe a mano",10],["Aclarar y poner a escurrir",5],["Secar la encimera",2]]},
 "cambiar_sabanas": {"ex":["cambiar las sabanas","poner sabanas limpias","hacer la cama con ropa limpia","cambiar la ropa de cama"],
   "steps":[["Quitar sabanas y fundas usadas",3],["Meterlas a lavar",2],["Poner el juego limpio",8],["Colocar la colcha y los cojines",3]]},
 "planchar": {"ex":["planchar la ropa","planchar las camisas","planchar lo del cesto","quitar arrugas a la ropa"],
   "steps":[["Montar la tabla y calentar la plancha",3],["Separar por tipo de prenda",4],["Planchar de menos a mas delicado",20],["Colgar segun se planchan",6]]},
 "sacar_basura": {"ex":["sacar la basura","bajar el reciclaje","tirar las bolsas de basura","separar el reciclaje","sacar el cubo"],
   "steps":[["Reunir bolsas de cada cubo: %s",3],["Separar carton, vidrio y organico",4],["Bajar al contenedor correcto",5],["Poner bolsas nuevas en los cubos",2]]},
 "limpiar_nevera": {"ex":["limpiar la nevera","ordenar el frigorifico","tirar lo caducado de la nevera","limpiar el frigo por dentro"],
   "steps":[["Sacar todo y revisar fechas",8],["Tirar lo caducado o malo",5],["Limpiar baldas y cajones",12],["Colocar por orden y visibilidad",6]]},
 "limpiar_cristales": {"ex":["limpiar los cristales","limpiar las ventanas","limpiar los espejos","dejar los cristales sin marcas"],
   "steps":[["Preparar limpiacristales y bayeta: %s",3],["Quitar el polvo del marco",4],["Aplicar y arrastrar de arriba a abajo",12],["Repasar esquinas y marcas",5]]},
 "aspirar": {"ex":["aspirar la casa","pasar la aspiradora","aspirar el salon","limpiar el suelo con la aspiradora"],
   "steps":[["Recoger objetos del suelo: %s",5],["Vaciar el deposito si hace falta",3],["Aspirar habitacion por habitacion",15],["Pasar por rincones y bajo muebles",6]]},
 "organizar_armario": {"ex":["organizar el armario","ordenar la ropa del armario","hacer el cambio de armario","doblar y colocar la ropa"],
   "steps":[["Sacar y agrupar por tipo: %s",10],["Apartar lo que no uso hace un ano",10],["Doblar y colgar por categorias",15],["Guardar fuera de temporada",8]]},
 "decluttering": {"ex":["tirar cosas que no uso","hacer limpieza de trastos","despejar y donar cosas","deshacerme de lo que sobra","ordenar y tirar"],
   "steps":[["Elegir una zona pequena: %s",3],["Separar en quedar, donar y tirar",15],["Meter lo de donar en una bolsa",5],["Tirar la basura y llevar la donacion",10]]},
 "montar_mueble": {"ex":["montar el mueble","armar la estanteria de ikea","montar la mesa nueva","montar una comoda"],
   "steps":[["Abrir la caja y contar piezas: %s",6],["Leer las instrucciones enteras",5],["Separar tornillos por pasos",4],["Montar siguiendo el orden",35],["Fijar a la pared si toca",8]]},
 "regar_plantas": {"ex":["regar las plantas","cuidar las macetas","regar el jardin","echar agua a las plantas"],
   "steps":[["Comprobar cuales necesitan agua: %s",3],["Llenar la regadera",2],["Regar sin encharcar",8],["Quitar hojas secas",4]]},
 "pasear_perro": {"ex":["pasear al perro","sacar al perro","dar un paseo con el perro","llevar al perro a la calle"],
   "steps":[["Coger correa, bolsas y agua",2],["Salir a la ruta habitual",20],["Dejar que huela y haga sus cosas",5],["Recoger y volver",5]]},
 "limpiar_horno": {"ex":["limpiar el horno","desengrasar el horno","limpiar la vitroceramica","limpiar los fogones"],
   "steps":[["Aplicar desengrasante y dejar actuar: %s",5],["Quitar y remojar las rejillas",8],["Frotar el interior",12],["Aclarar y secar",6]]},
 "pintar_habitacion": {"ex":["pintar la habitacion","pintar el cuarto","dar una mano de pintura","pintar la pared","pintar el salon","repintar la pared del cuarto"],
   "steps":[["Comprar pintura y material: %s",20],["Cubrir muebles y suelo con plastico",15],["Poner cinta en bordes y marcos",15],["Dar la primera mano",40],["Dar la segunda mano y retirar cinta",40]]},
 "colgar_cosas": {"ex":["colgar los cuadros","poner una estanteria en la pared","colgar el espejo","montar unas baldas"],
   "steps":[["Decidir la posicion y marcar con lapiz: %s",6],["Comprobar que no hay cables detras",3],["Taladrar y poner tacos",10],["Atornillar el soporte",8],["Colgar y nivelar",5]]},
 "arreglar_averia": {"ex":["llamar al fontanero","arreglar la averia","reparar la fuga de agua","llamar a un tecnico","arreglar la caldera"],
   "steps":[["Anotar el problema y cuando pasa: %s",4],["Buscar un profesional o el seguro",8],["Pedir presupuesto o cita",8],["Estar en casa para la visita",30],["Guardar factura y garantia",3]]},
 "ordenar_trastero": {"ex":["ordenar el trastero","vaciar el garaje","organizar el almacen","despejar el desvan"],
   "steps":[["Sacar todo a la vista: %s",20],["Agrupar por categorias",15],["Tirar o donar lo inservible",20],["Colocar en baldas y etiquetar cajas",25]]},
 "bricolaje_pequeno": {"ex":["cambiar una bombilla","apretar un tornillo","arreglar la puerta que chirria","poner una pila","pequena reparacion en casa"],
   "steps":[["Identificar exactamente que falla: %s",3],["Reunir la herramienta necesaria",4],["Hacer el arreglo",10],["Probar que funciona",2]]},
 "planificar_menu": {"ex":["planificar el menu de la semana","organizar las comidas de la semana","hacer el menu semanal","decidir que cocinar esta semana"],
   "steps":[["Mirar que hay ya en casa",6],["Elegir platos para cada dia: %s",15],["Anotar los ingredientes que faltan",8],["Pasar la lista a la compra",4]]},
 "hornear": {"ex":["hacer un bizcocho","hornear galletas","hacer una tarta","preparar un postre al horno","hacer pan casero"],
   "steps":[["Sacar ingredientes y utensilios: %s",6],["Precalentar el horno",3],["Preparar la masa siguiendo la receta",20],["Hornear y vigilar",30],["Enfriar antes de desmoldar",10]]},
 "comida_invitados": {"ex":["preparar la comida para invitados","cocinar para la cena de invitados","hacer la comida de la reunion familiar"],
   "steps":[["Decidir el menu y numero de personas: %s",10],["Comprar lo que falte",30],["Preparar lo que se pueda la vispera",40],["Cocinar el dia y emplatar",60],["Poner la mesa",15]]},
 "declaracion_renta": {"ex":["hacer la declaracion de la renta","presentar la renta","hacer los impuestos","declarar a hacienda"],
   "steps":[["Reunir certificados y datos fiscales: %s",20],["Entrar en el borrador de Hacienda",10],["Revisar deducciones que me aplican",20],["Confirmar y presentar",10],["Guardar el justificante",3]]},
 "presupuesto_mensual": {"ex":["hacer el presupuesto del mes","organizar las finanzas","cuadrar los gastos del mes","planificar el dinero del mes"],
   "steps":[["Anotar ingresos fijos: %s",5],["Listar gastos fijos y variables",12],["Asignar un limite a cada categoria",10],["Apartar ahorro primero",4],["Revisar a final de mes",6]]},
 "cancelar_suscripcion": {"ex":["cancelar una suscripcion","dar de baja el gimnasio","cancelar netflix","anular una suscripcion que no uso"],
   "steps":[["Localizar donde se gestiona: %s",5],["Leer condiciones de baja",6],["Cancelar y pedir confirmacion por escrito",8],["Comprobar que no vuelven a cobrar",3]]},
 "reclamacion": {"ex":["poner una reclamacion","reclamar un cobro indebido","reclamar a la compania","hacer una hoja de reclamaciones"],
   "steps":[["Reunir pruebas y fechas: %s",10],["Escribir la reclamacion clara y breve",15],["Enviarla por el canal oficial",8],["Guardar copia y numero de expediente",3],["Anotar cuando reclamar de nuevo",2]]},
 "contratar_seguro": {"ex":["contratar un seguro","buscar seguro del coche","comparar seguros de hogar","renovar el seguro"],
   "steps":[["Definir que quiero cubrir: %s",8],["Pedir 3 presupuestos",20],["Comparar coberturas y letra pequena",15],["Contratar el elegido",10]]},
 "cambiar_compania": {"ex":["cambiar de compania de luz","cambiar de operador de internet","cambiar de tarifa movil","darme de alta con otra compania"],
   "steps":[["Mirar mi consumo y factura actual: %s",8],["Comparar ofertas",15],["Contratar la nueva",12],["Confirmar la portabilidad y baja de la antigua",5]]},
 "revisar_gastos": {"ex":["revisar los gastos del banco","mirar en que gasto","revisar los extractos","controlar los gastos"],
   "steps":[["Descargar el extracto del mes: %s",4],["Clasificar los gastos por tipo",12],["Detectar gastos raros o de mas",6],["Decidir un recorte",4]]},
 "pedir_presupuesto": {"ex":["pedir presupuesto para la reforma","pedir varios presupuestos","pedir presupuesto a un profesional"],
   "steps":[["Describir bien lo que necesito: %s",8],["Buscar 3 profesionales",10],["Pedir presupuesto a cada uno",12],["Comparar y elegir",8]]},
 "escanear_documentos": {"ex":["escanear los documentos","digitalizar los papeles","escanear el contrato","pasar papeles a pdf"],
   "steps":[["Reunir los documentos: %s",5],["Escanear con la app del movil",10],["Renombrar los archivos con claridad",6],["Guardarlos en la carpeta y hacer copia",4]]},
 "backup_datos": {"ex":["hacer una copia de seguridad","hacer backup del movil","guardar mis archivos importantes","respaldar las fotos"],
   "steps":[["Elegir que respaldar: %s",5],["Conectar disco o nube",4],["Lanzar la copia",20],["Verificar que se copio bien",6]]},
 "actualizar_cv": {"ex":["actualizar el curriculum","poner al dia el cv","mejorar mi curriculum","hacer el cv nuevo"],
   "steps":[["Reunir logros y fechas recientes: %s",10],["Actualizar experiencia y aptitudes",15],["Ajustar el diseno a una pagina",12],["Exportar a PDF y revisar faltas",8]]},
 "buscar_trabajo": {"ex":["buscar trabajo","echar curriculos","apuntarme a ofertas","buscar empleo"],
   "steps":[["Definir puesto y filtros: %s",8],["Actualizar perfil de LinkedIn",15],["Seleccionar 5 ofertas que encajen",15],["Enviar candidaturas adaptadas",25],["Anotar donde apliqué",4]]},
 "preparar_entrevista": {"ex":["preparar la entrevista de trabajo","prepararme para la entrevista","ensayar la entrevista"],
   "steps":[["Investigar la empresa y el puesto: %s",15],["Preparar respuestas a preguntas tipicas",20],["Preparar 3 preguntas para ellos",8],["Elegir ropa y probar la conexion",8],["Ensayar en voz alta",15]]},
 "pedir_vacaciones": {"ex":["pedir las vacaciones","solicitar dias libres","pedir un dia de asuntos propios","gestionar mis vacaciones"],
   "steps":[["Mirar dias disponibles y fechas: %s",5],["Avisar al equipo con antelacion",5],["Solicitar por el canal oficial",6],["Dejar preparado lo que quede pendiente",15]]},
 "solicitar_beca": {"ex":["solicitar una beca","pedir una ayuda","rellenar la solicitud de beca","presentar la beca del ministerio"],
   "steps":[["Leer los requisitos y plazos: %s",12],["Reunir la documentacion",20],["Rellenar el formulario",20],["Revisar y enviar antes del plazo",10],["Guardar el resguardo",2]]},
 "firmar_documento": {"ex":["firmar el contrato","firmar unos papeles","revisar y firmar el documento","firmar digitalmente"],
   "steps":[["Leer el documento entero: %s",15],["Marcar dudas o cambios",8],["Firmar (a mano o con certificado)",6],["Enviar y guardar copia",4]]},
 "pedir_cita_peluqueria": {"ex":["pedir cita en la peluqueria","reservar en el barbero","pedir hora para cortarme el pelo"],
   "steps":[["Elegir peluqueria y servicio: %s",4],["Mirar mis huecos",3],["Reservar por app o telefono",5],["Apuntarlo en el calendario",2]]},
 "reservar_analitica": {"ex":["pedir cita para la analitica","reservar el analisis de sangre","sacar cita para analitica"],
   "steps":[["Buscar centro y horario en ayunas: %s",5],["Pedir la cita",6],["Anotar preparacion (ayuno, agua)",3],["Poner recordatorio la vispera",2]]},
 "meditar": {"ex":["meditar","hacer una meditacion","practicar mindfulness","hacer una pausa de respiracion"],
   "steps":[["Buscar un sitio tranquilo",2],["Poner un temporizador de 10 min",1],["Sentarse y centrarse en la respiracion",10],["Anotar como me siento",2]]},
 "rutina_sueno": {"ex":["mejorar mi rutina de sueno","preparar la rutina de dormir","irme antes a la cama","preparar la noche"],
   "steps":[["Fijar una hora de acostarse: %s",3],["Apagar pantallas 30 min antes",5],["Dejar preparado lo de manana",10],["Bajar luces y relajarme",15]]},
 "sesion_terapia": {"ex":["preparar la sesion de terapia","apuntar temas para el psicologo","prepararme para terapia"],
   "steps":[["Anotar lo que ha pasado esta semana: %s",8],["Marcar 2 temas prioritarios",5],["Revisar los deberes de la ultima sesion",5],["Ir a la sesion",50]]},
 "planificar_dieta": {"ex":["planificar la dieta","organizar mis comidas saludables","preparar un plan de alimentacion","cuidar la alimentacion"],
   "steps":[["Fijar el objetivo y limites: %s",8],["Elegir platos saludables que me gusten",15],["Hacer la lista de la compra acorde",8],["Preparar comidas por adelantado",30]]},
 "apuntarse_gimnasio": {"ex":["apuntarme al gimnasio","inscribirme en el gym","buscar un gimnasio cerca","empezar en el gimnasio"],
   "steps":[["Buscar gimnasios cercanos y precios: %s",10],["Ir a ver uno o pedir el pase de prueba",30],["Inscribirme",10],["Reservar la primera sesion",5]]},
 "vacunarse": {"ex":["ponerme la vacuna","pedir cita para vacunarme","vacuna de la gripe"],
   "steps":[["Comprobar que vacuna me toca: %s",5],["Pedir cita en el centro",6],["Ir a vacunarme",20],["Anotar la fecha para la proxima",2]]},
 "planificar_semana": {"ex":["planificar la semana","organizar la semana que viene","hacer la revision semanal","preparar la semana"],
   "steps":[["Repasar lo que quedo pendiente: %s",8],["Mirar citas y fechas limite",6],["Elegir las 3 prioridades de la semana",6],["Repartirlas por dias segun energia",10]]},
 "planificar_dia": {"ex":["planificar el dia","organizar el dia de hoy","preparar el dia","hacer el plan de hoy"],
   "steps":[["Mirar citas fijas de hoy",3],["Elegir la tarea mas importante",3],["Colocar el resto por energia",5],["Empezar por la primera",1]]},
 "investigar_tema": {"ex":["investigar un tema","documentarme sobre algo","buscar informacion para el trabajo","hacer research"],
   "steps":[["Definir la pregunta concreta: %s",5],["Buscar 3-4 fuentes fiables",15],["Tomar notas de lo util",20],["Resumir las conclusiones",10]]},
 "tomar_apuntes": {"ex":["pasar los apuntes a limpio","resumir el tema","hacer un resumen","organizar los apuntes"],
   "steps":[["Reunir el material: %s",4],["Leer y subrayar lo clave",15],["Escribir el resumen con tus palabras",20],["Anadir un esquema o mapa",8]]},
 "entregar_proyecto": {"ex":["entregar el proyecto","terminar y entregar el trabajo","cerrar el proyecto y enviarlo"],
   "steps":[["Repasar los requisitos de entrega: %s",8],["Completar lo que falte",30],["Revisar calidad y formato",15],["Entregar por el canal correcto",5],["Confirmar recepcion",3]]},
 "trabajo_en_grupo": {"ex":["organizar el trabajo en grupo","coordinar el trabajo de equipo","repartir el trabajo del grupo"],
   "steps":[["Definir el objetivo comun: %s",6],["Repartir tareas por persona",10],["Fijar fechas y punto de reunion",6],["Hacer mi parte",40],["Juntar y revisar todo",20]]},
 "preparar_oposicion": {"ex":["estudiar la oposicion","preparar las oposiciones","organizar el temario de la oposicion"],
   "steps":[["Descargar el temario y fechas: %s",10],["Hacer un plan de estudio por semanas",20],["Estudiar el bloque de hoy",50],["Hacer un test de repaso",20]]},
 "tfg_tfm": {"ex":["avanzar el tfg","escribir el trabajo de fin de grado","seguir con el tfm","hacer la tesis"],
   "steps":[["Fijar el objetivo de esta sesion: %s",5],["Revisar lo escrito y las notas del tutor",15],["Escribir el siguiente apartado",45],["Guardar y anotar el siguiente paso",5]]},
 "aprender_software": {"ex":["aprender a usar excel","aprender una herramienta nueva","aprender el programa del trabajo","dominar una app"],
   "steps":[["Definir que necesito hacer con ella: %s",6],["Ver un tutorial corto",20],["Probarlo con un caso real",25],["Anotar los atajos que uso",6]]},
 "leer_documentacion": {"ex":["leer la documentacion","estudiar el manual","leerme la guia","revisar la documentacion tecnica"],
   "steps":[["Ojear el indice y lo relevante: %s",6],["Leer el apartado clave",20],["Probar lo leido si aplica",15],["Anotar lo importante",6]]},
 "dar_feedback": {"ex":["dar feedback a un companero","escribir una valoracion","preparar el feedback del equipo"],
   "steps":[["Anotar hechos concretos, no juicios: %s",8],["Equilibrar lo positivo y lo mejorable",6],["Redactar o preparar la conversacion",10],["Darlo con respeto y en privado",15]]},
 "curso_online": {"ex":["hacer un curso online","empezar un curso","seguir con el curso de internet","terminar el curso"],
   "steps":[["Fijar cuantas lecciones por sesion: %s",4],["Ver la leccion tomando notas",25],["Hacer el ejercicio o test",15],["Marcar donde retomar",3]]},
 "felicitar_cumple": {"ex":["felicitar un cumpleanos","escribir la felicitacion","mandar un mensaje de cumpleanos"],
   "steps":[["Pensar algo personal que decir: %s",4],["Escribir el mensaje o tarjeta",6],["Enviarlo o entregarlo",2]]},
 "mensaje_dificil": {"ex":["escribir un mensaje dificil","mandar un mensaje incomodo","contestar un mensaje delicado","responder algo dificil"],
   "steps":[["Aclarar que quiero conseguir: %s",5],["Escribir un borrador sin enviar",10],["Quitar lo que sobra y suavizar el tono",8],["Releer en frio y enviar",4]]},
 "conversacion_dificil": {"ex":["tener una conversacion dificil","hablar algo incomodo con alguien","afrontar una charla complicada"],
   "steps":[["Definir el objetivo y limites: %s",8],["Anotar lo que quiero decir con calma",10],["Elegir momento y lugar tranquilo",5],["Tener la conversacion escuchando",30]]},
 "organizar_boda": {"ex":["organizar la boda","preparar la boda","planificar el enlace"],
   "steps":[["Fijar fecha, presupuesto e invitados: %s",30],["Reservar sitio y proveedores clave",60],["Enviar invitaciones",30],["Cerrar detalles (menu, musica, deco)",60],["Confirmar todo la semana antes",30]]},
 "planear_finde": {"ex":["planear el fin de semana","organizar el finde","decidir que hacer el sabado","planear una escapada corta"],
   "steps":[["Decidir plan y con quien: %s",6],["Mirar horarios, tiempo o entradas",10],["Reservar lo que haga falta",10],["Anotarlo en el calendario",3]]},
 "visitar_familia": {"ex":["ir a ver a mis padres","visitar a la familia","organizar la visita a mis abuelos"],
   "steps":[["Acordar dia y hora: %s",5],["Mirar transporte o coche",6],["Preparar lo que llevo",10],["Ir a la visita",90]]},
 "cita_pareja": {"ex":["organizar una cita con mi pareja","planear una cena romantica","preparar una cita especial"],
   "steps":[["Decidir el plan y sorpresa: %s",8],["Reservar sitio o preparar en casa",15],["Cuadrar horario con la otra persona",4],["Preparar los detalles",20]]},
 "escribir_carta": {"ex":["escribir una carta","redactar una carta a mano","escribir una carta formal"],
   "steps":[["Aclarar el destinatario y el motivo: %s",4],["Anotar los puntos a decir",6],["Escribir la carta",20],["Revisar y enviarla",8]]},
 "hacer_videollamada": {"ex":["hacer una videollamada","llamar por video a la familia","preparar una videollamada"],
   "steps":[["Acordar hora y app: %s",4],["Comprobar camara, micro y conexion",5],["Hacer la llamada",30]]},
 "quedar_amigos": {"ex":["quedar con los amigos","organizar una quedada","proponer un plan al grupo","montar un plan con amigos"],
   "steps":[["Proponer plan y fechas al grupo: %s",6],["Cerrar dia y sitio con la mayoria",8],["Reservar si hace falta",8],["Confirmar el dia antes",3]]},
 "comprar_online": {"ex":["comprar algo por internet","hacer un pedido online","comprar en amazon","hacer una compra online"],
   "steps":[["Definir que necesito y presupuesto: %s",5],["Comparar 2-3 opciones y opiniones",12],["Anadir al carrito y revisar total",5],["Pagar y guardar el email de compra",4]]},
 "devolucion": {"ex":["devolver una compra","hacer una devolucion","devolver un paquete","gestionar la devolucion"],
   "steps":[["Buscar la politica y el plazo: %s",5],["Iniciar la devolucion en la web",6],["Empaquetar con la etiqueta",8],["Llevarlo al punto de envio",15],["Comprobar el reembolso",3]]},
 "vender_segunda_mano": {"ex":["vender algo en wallapop","poner cosas de segunda mano","vender lo que no uso","subir productos a vender"],
   "steps":[["Elegir que vender y limpiarlo: %s",10],["Hacer buenas fotos",10],["Escribir titulo, descripcion y precio",10],["Publicar y responder mensajes",15],["Quedar para la entrega",10]]},
 "comparar_precios": {"ex":["comparar precios","mirar donde esta mas barato","buscar la mejor oferta","comparar antes de comprar"],
   "steps":[["Definir el producto exacto: %s",4],["Mirar en 3 tiendas o comparadores",12],["Tener en cuenta envio y garantia",5],["Elegir la mejor opcion",3]]},
 "renovar_movil": {"ex":["cambiar de movil","comprar un movil nuevo","renovar el telefono","elegir un movil"],
   "steps":[["Fijar presupuesto y lo que necesito: %s",8],["Comparar 3 modelos",20],["Comprar el elegido",10],["Pasar los datos del viejo",25]]},
 "comprar_ropa": {"ex":["comprar ropa","renovar el armario","comprarme unos pantalones","ir de compras de ropa"],
   "steps":[["Anotar que necesito de verdad: %s",5],["Mirar tallas y opciones",15],["Probar o comprar con opcion a devolver",30],["Quitar etiquetas y guardar recibo",5]]},
 "reservar_restaurante": {"ex":["reservar mesa en un restaurante","reservar para cenar","hacer una reserva en un sitio"],
   "steps":[["Elegir sitio segun ocasion: %s",6],["Mirar disponibilidad y horario",5],["Reservar por app o telefono",5],["Anotar la reserva",2]]},
 "sacar_entradas": {"ex":["sacar entradas para el concierto","comprar entradas del cine","reservar entradas","pillar entradas para el partido"],
   "steps":[["Fijar dia, hora y con quien: %s",4],["Entrar en la web oficial a tiempo",6],["Elegir asientos y comprar",8],["Guardar las entradas en el movil",3]]},
 "sacar_billetes": {"ex":["comprar billetes de tren","sacar los billetes de bus","reservar el ave","comprar el billete de avion"],
   "steps":[["Fijar fechas y horarios: %s",6],["Comparar precios y compania",12],["Comprar el billete",8],["Guardar el billete y poner recordatorio",3]]},
 "planear_excursion": {"ex":["planear una excursion","organizar una ruta de senderismo","preparar una salida al campo","planear un dia de montana"],
   "steps":[["Elegir destino y dificultad: %s",8],["Mirar tiempo, ruta y transporte",12],["Preparar mochila, agua y comida",15],["Avisar a alguien de la ruta",3]]},
 "comida_familiar": {"ex":["organizar la comida familiar","preparar la comida de navidad","montar una comida con la familia"],
   "steps":[["Acordar fecha e invitados: %s",8],["Decidir el menu entre todos",10],["Repartir quien trae que",8],["Preparar la casa y la mesa",30]]},
 "reservar_actividad": {"ex":["reservar una actividad","apuntarme a una clase","reservar plaza en un taller","reservar spa"],
   "steps":[["Elegir la actividad y fecha: %s",5],["Comprobar plazas y precio",5],["Reservar y pagar si toca",6],["Anotarla en el calendario",2]]},
 "coche_taller": {"ex":["llevar el coche al taller","pasar la itv","hacer la revision del coche","cambiar el aceite del coche"],
   "steps":[["Anotar que hay que revisar: %s",4],["Pedir cita en el taller o ITV",6],["Llevar el coche",20],["Recogerlo y guardar factura",15]]},
 "lavar_coche": {"ex":["lavar el coche","limpiar el coche por dentro","llevar el coche al tunel de lavado"],
   "steps":[["Sacar la basura del interior: %s",5],["Aspirar por dentro",10],["Lavar la carroceria",15],["Secar y limpiar cristales",8]]},
 "cambiar_neumaticos": {"ex":["cambiar los neumaticos","poner ruedas nuevas","cambiar las ruedas de invierno"],
   "steps":[["Comprobar la medida de neumatico: %s",5],["Pedir presupuesto en 2 sitios",10],["Reservar cita",5],["Llevar el coche al cambio",40]]},
 "recurrir_multa": {"ex":["recurrir una multa","alegar la multa de trafico","poner un recurso a la multa"],
   "steps":[["Leer bien la multa y el plazo: %s",8],["Reunir pruebas a favor",10],["Escribir las alegaciones",15],["Presentar el recurso",8]]},
 "carnet_conducir": {"ex":["sacarme el carnet de conducir","apuntarme a la autoescuela","empezar las clases de conducir"],
   "steps":[["Buscar autoescuela y precio: %s",12],["Matricularme y pedir el psicotecnico",20],["Estudiar el teorico",40],["Reservar practicas y examenes",15]]},
 "organizar_fotos": {"ex":["organizar las fotos","ordenar la galeria del movil","borrar fotos repetidas","hacer albumes de fotos"],
   "steps":[["Borrar borrosas y repetidas: %s",15],["Agrupar por eventos o albumes",15],["Hacer copia de seguridad",10],["Elegir las mejores para imprimir",8]]},
 "liberar_espacio": {"ex":["liberar espacio en el movil","limpiar el almacenamiento","el movil esta lleno","borrar cosas del telefono"],
   "steps":[["Ver que ocupa mas espacio: %s",5],["Borrar apps que no uso",8],["Vaciar cache y descargas",6],["Subir fotos a la nube y borrar del movil",12]]},
 "configurar_dispositivo": {"ex":["configurar el movil nuevo","poner a punto el ordenador nuevo","instalar y configurar el portatil"],
   "steps":[["Pasar los datos del anterior: %s",25],["Instalar apps imprescindibles",20],["Configurar cuentas y copias",15],["Ajustar privacidad y notificaciones",10]]},
 "cambiar_contrasenas": {"ex":["cambiar las contrasenas","mejorar la seguridad de mis cuentas","actualizar mis passwords","poner un gestor de contrasenas"],
   "steps":[["Listar las cuentas importantes: %s",6],["Instalar un gestor de contrasenas",10],["Cambiar las claves debiles o repetidas",25],["Activar la verificacion en dos pasos",12]]},
 "cerrar_cuentas": {"ex":["cerrar cuentas que no uso","borrar cuentas viejas","darme de baja de servicios online"],
   "steps":[["Listar las cuentas a cerrar: %s",8],["Descargar mis datos si los quiero",10],["Cerrar cada cuenta",15],["Confirmar y anotar",4]]},
 "hoja_calculo": {"ex":["hacer una hoja de calculo","montar un excel","crear una tabla de datos","hacer una plantilla en excel"],
   "steps":[["Definir que quiero calcular: %s",6],["Montar columnas y encabezados",10],["Meter los datos",20],["Anadir formulas y formato",15]]},
 "organizar_archivos": {"ex":["organizar los archivos del ordenador","ordenar las carpetas","limpiar el escritorio del pc","poner orden en los documentos"],
   "steps":[["Crear una estructura de carpetas: %s",8],["Mover cada archivo a su sitio",20],["Borrar duplicados y basura",10],["Vaciar la papelera",2]]},
 "aprender_idioma": {"ex":["estudiar ingles","practicar un idioma","aprender frances","avanzar con el idioma"],
   "steps":[["Fijar la meta de hoy: %s",3],["Repasar el vocabulario nuevo",12],["Hacer una leccion o ejercicios",20],["Practicar hablando o escribiendo",10]]},
 "practicar_instrumento": {"ex":["practicar guitarra","tocar el piano un rato","ensayar con el instrumento","practicar musica"],
   "steps":[["Preparar el instrumento y afinar: %s",5],["Calentar con escalas",8],["Trabajar el trozo dificil despacio",20],["Tocar entero para disfrutar",10]]},
 "pintar_cuadro": {"ex":["pintar un cuadro","dibujar algo","hacer una ilustracion","ponerme a pintar"],
   "steps":[["Preparar material y espacio: %s",8],["Bocetar la idea",15],["Pintar por capas o zonas",45],["Dejar secar y firmar",5]]},
 "editar_video": {"ex":["editar un video","montar un video","editar el video para youtube","hacer el montaje del video"],
   "steps":[["Revisar el material grabado: %s",10],["Seleccionar y ordenar los cortes",25],["Anadir musica, textos y transiciones",30],["Exportar y revisar",15]]},
 "escribir_novela": {"ex":["escribir mi novela","avanzar el libro","seguir con la historia","escribir un capitulo"],
   "steps":[["Releer el final anterior: %s",8],["Fijar que pasa en esta escena",6],["Escribir sin corregir",40],["Guardar y anotar el siguiente paso",4]]},
 "manualidad_diy": {"ex":["hacer una manualidad","un proyecto de diy","hacer algo con las manos","montar una manualidad"],
   "steps":[["Elegir el proyecto y ver material: %s",8],["Reunir o comprar lo que falte",20],["Seguir los pasos con calma",40],["Recoger y limpiar",8]]},
 "huerto": {"ex":["montar un huerto","plantar tomates","cuidar el huerto","empezar un huerto urbano"],
   "steps":[["Elegir que plantar y donde: %s",10],["Preparar tierra y macetas",20],["Sembrar o plantar",20],["Regar y poner recordatorio de cuidados",6]]},
 "ensayar_actuacion": {"ex":["ensayar la actuacion","practicar el discurso","ensayar la obra","preparar el bolo"],
   "steps":[["Repasar el texto o guion: %s",15],["Ensayar por partes",25],["Ensayar entero cronometrando",20],["Corregir lo que falla",10]]},
 "deberes_hijos": {"ex":["ayudar con los deberes","hacer los deberes con mi hijo","supervisar las tareas del cole"],
   "steps":[["Ver que deberes hay hoy: %s",4],["Preparar un sitio sin distracciones",4],["Hacerlos por asignatura",25],["Revisar y meter en la mochila",5]]},
 "mochila_cole": {"ex":["preparar la mochila del cole","dejar lista la mochila","preparar las cosas del cole"],
   "steps":[["Mirar el horario de manana: %s",3],["Meter libros y material",5],["Preparar almuerzo y agua",5],["Dejarla en la puerta",1]]},
 "actividad_ninos": {"ex":["organizar una actividad con los ninos","planear algo para los peques","preparar un plan para los ninos"],
   "steps":[["Elegir plan segun edad y tiempo: %s",6],["Preparar material o entradas",10],["Avisar y cuadrar horarios",5],["Hacer la actividad",60]]},
 "disfraz": {"ex":["preparar un disfraz","hacer el disfraz de carnaval","montar el disfraz para la fiesta"],
   "steps":[["Decidir el disfraz: %s",6],["Ver que tengo y que falta",8],["Comprar o improvisar lo que falte",20],["Montarlo y probarlo",20]]},
 "donar_sangre": {"ex":["ir a donar sangre","apuntarme a donar sangre","donar sangre"],
   "steps":[["Buscar punto de donacion y horario: %s",5],["Comprobar que cumplo requisitos",4],["Comer e hidratarme antes",15],["Ir a donar",40]]},
 "reciclar_objetos": {"ex":["llevar cosas al punto limpio","reciclar aparatos viejos","tirar pilas y electronica","llevar ropa a reciclar"],
   "steps":[["Reunir lo que hay que reciclar: %s",8],["Separar por tipo (pilas, ropa, electronica)",6],["Buscar el punto correcto",5],["Llevarlo",20]]},
 "renovar_documento": {"ex":["renovar el carnet de conducir","renovar el dni","renovar la tarjeta sanitaria","renovar documentos"],
   "steps":[["Ver que documentos y fotos pide: %s",6],["Reunir papeles y foto",15],["Pedir cita",8],["Ir a renovar y pagar la tasa",30]]},
 "hacer_gestion_online": {"ex":["hacer una gestion online","entrar en la sede electronica","hacer un tramite por internet con certificado"],
   "steps":[["Comprobar que tengo certificado o clave: %s",6],["Entrar en la sede y buscar el tramite",8],["Rellenar y adjuntar documentos",15],["Firmar, enviar y guardar el justificante",6]]},
}
